### ISSUE TITLE
App: Galaxpay (publicação)

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-galaxpay#16]
- [x] Token de parceiro para publicação no https://market.e-com.plus/ ;
> @vitorrgg favor cadatrar o @wisley7l como parceiro por favor, aí @wisley7l  coloca o token da sua conta nos secrets do repositório.
- [x] Descrição e um ícone legal (@vitorrgg ) pro Market (instruções [aqui](https://github.com/ecomplus/app-galaxpay#optional-setup-for-market));
- [x] Selo para a lista de formas de pagamento (@vitorrgg ), lembrando que as formas de pagamento do app serão sempre recorrentes (assinaturas), talvez o selo deva ter algo de diferente dos outros apps;

**Comment by vitorrgg** [comment]
![galaxpay](https://user-images.githubusercontent.com/35348281/160412986-51722812-0cbe-4be3-9e49-e145895e8c4a.png)

**Comment by vitorrgg** [comment]
Sobre o selo, o logo deles já tem uma ilustração referente a recorrência. O que pensei em fazer foi algo assim:

![galax](https://user-images.githubusercontent.com/35348281/160431554-66ecbbc2-8e79-4c00-8f03-4691bbff1d58.png)

**Comment by vitorrgg** [comment]
![galax](https://user-images.githubusercontent.com/35348281/160431883-78d76487-bbee-4f6e-b5f0-dac8082bd11b.png)

**Comment by leomp12** [comment]
Acho que o cadeado você poderia manter, quando eu falei de talvez fazer diferente era escrever que é uma assinatura em algum lugar...
Esse ícone aí não me faz pensar em assinatura não 😄

**Comment by vitorrgg** [comment]
Segue uma sugestão de descrição @wisley7l . Sugiro adicionar algo que julgue relevante, principalmente se for alguma feature

Pagamentos recorrentes com cartão de crédito ou boleto bancário através da [Vindi](https://vindi.com.br/):


- Integração direta com o Gateway da Galaxpay;
- Suporta integração com diversos adiquirentes (VISA, MasterCard, Diners, Discover, Elo, Amex, Aura, HIpercard, JCB, Hiper, Credz, Cabal, Sorocred, Credsystem, Banescard)
- Atualização automática de status da transação;
- Parcelamento com e/ou sem juros;
- Desconto fixo ou percentual por forma de pagamento;
- Personalizações opcionais para o checkout;

**Configuração**

Configure seu ID e hash de acesso a API do Galaxpay, que são obtidos através de [solicitação no suporte](https://docs.galaxpay.com.br/suporte). Seu Public Token para Tokenização de Cartão, é disponivél no Dashbord do GalaxPay, sessão de modulos, configuração de WebServices

**Comment by vitorrgg** [comment]
![galax](https://user-images.githubusercontent.com/35348281/160503898-859f006d-262a-4b0d-ab5b-77f2210fd019.png)

**Comment by leomp12** [comment]
Editei umas coisas na descrição https://github.com/ecomplus/app-galaxpay/blob/master/hosting/description.md

**Comment by leomp12** [comment]
E o app está publicado 👍🏾 
Boa!
https://app.e-com.plus/#/apps/edit/123188/
![Screenshot 2022-03-28 at 23-35-45 E-Com Plus Dashboard App](https://user-images.githubusercontent.com/10326572/160521437-abeeffe2-3801-4fe0-9b39-8bea215582ca.png)
