### ISSUE TITLE
Inserção de pagamentos com períodos diferentes

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-galaxpay#17]
Atualmente, o aplicativo limita o uso para um período apenas de pagamentos, ou seja, se o cliente quiser fazer opções mensais, semestrais e anuais, não é possível, permite apenas uma das modalidades.

Logo, sugere-se que o cliente consiga realizar essa configuração.
Em que no aplicativo, o mesmo conseguirá oferecer quais quer periodicidades de pagamento que deverão ser mostradas via list_payments.

**Comment by leomp12** [comment]
@wisley7l aproveita que você vai ter que editar o admin settings e corrige esse enum por favor https://github.com/ecomplus/app-galaxpay/blob/master/functions/ecom.config.js#L270-L278

Isso é renderizado para o usuário exatamente dessa forma aí, e escrever _biweekly_ pro lojista definitivamente não é bom, nos enums no admin settings use valores claros para o usuário, no código você faz o parse com um switch case:

```js
let periodicity
switch (config.periodicity) {
  case 'Semanal':
    periodicity = 'weekly'
    break
  case 'Bissemanal':
    periodicity = 'biweekly'
    break
  // ...
  default:
    periodicity = config.periodicity
}
```

**Comment by leomp12** [comment]
E tente manter o suporte na função ao admin settings atual com o objeto `plan_recurrence` pra não quebrar usuários quando você atualizar o app.
Mesmo que o objeto `plan_recurrence` deixe de existir (e deve deixar, em favor de um array de objetos, certo ?) nas opções de configuração novas.

**Comment by wisley7l** [comment]
A inserção de desconto e dos planos foram criados. 
Também criado suporte para usuários que utilizavam a versão anterior.

**Comment by leomp12** [comment]
Boa @wisley7l !
@matheusgnreis faz um teste aí e fecha o issue por favor?

**Comment by matheusgnreis** [comment]
@wisley7l eu criei 3 regras aqui, mensal, trimestral e semestral, porém no checkout só aparece mensal. Tô testando na 1011, preciso instalar o app para uma mais recente? Não instalei de novo, por conta que no app anterior só permitia criar uma possibilidade no admin settings e o que está lá são quantos eu configurar

**Comment by wisley7l** [comment]
@matheusgnreis, acredito que o melhor seria atualizar o app na loja sim.
