### ISSUE TITLE
Webhook para assinatura cancelada

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-galaxpay#53]
Em alguns casos (talvez a maioria) o lojista vai cancelar a assinatura no painel do Galaxpay, e então precisamos atualizar o respectivo pedido na plataforma.
Recebendo o webhook informando o cancelamento da assinatura muda o status do pedido original para `{ status: 'cancelled' }` (status financeiro permanece o mesmo).

**Comment by wisley7l** [comment]
Melhoria realizada no [commit](https://github.com/ecomplus/app-galaxpay/commit/f8c9ba950d190326f37dd76e2fab2109fa96b6f0)

**Comment by leomp12** [comment]
Boa!
